### PR TITLE
Add August updates

### PR DESCRIPTION
**Pull request by astrojuanlu**
cc @jorgepiloto @Yash-10

### CODE REVIEW

**Review by Yash-10 — APPROVED** [review]
:rocket: Do you think we can add about the upcoming events user guide, which might be merged soon?

**Comment by astrojuanlu** [comment]
Fair enough!

**Comment by astrojuanlu** [comment]
Done ✔️

**Comment by astrojuanlu** [comment]
If there are no more comments, I'm merging this 💪🏽

**Pull request merged**
